# docker-compose.yml
version: '3.8'

services:
  faceswap-api:
    build: .
    container_name: faceswap-api
    ports:
      - "8000:8000"
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./arcface_model:/app/arcface_model
      - ./insightface_func:/app/insightface_func
      - ./temp:/app/temp
      - ./output:/app/output
      - ./lfw_funneled:/app/lfw_funneled  # your dataset
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s